### ISSUE TITLE
Simplify fractional calls

### ISSUE THREAD

**Issue by infusion** [redelmann/Aleatory.js#1]
Hi,

Aleatory.js is a really nice project! I just read over it and noticed, that you could simplify the calls to Fraction.js by calling the constructor only if it's really needed.

For example:
`q.equals(new Fraction(1))` can be written as `q.equals(1)`

or
`new Fraction(x).mul(new Fraction(x))` as `new Fraction(x).mul(x)`

or
`mean.add(new Fraction(item.value).mul(item.probability))` as `mean.add(item.probability.mul(item.value))`

This can speed things up a bit as no new objects must be created, but also simplifies your code a bit :)

Robert

**Comment by redelmann** [comment]
Hi Robert!

Thanks for the suggestion and the kind words. I will look into this!

Best,

Romain

**Comment by redelmann** [comment]
Finally got around doing this. Thanks for the suggestion!
